### ISSUE TITLE
BadCredentialsException when attempting to send action with params via websocket

### ISSUE THREAD

**Issue by Mekadrom** [Mekadrom/uhoma#34]
```
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:208) ~[na:na]
        at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1186) ~[na:na]
        at java.base/java.util.Map.of(Map.java:1445) ~[na:na]
        at com.higgs.server.web.socket.NodeSocket.buildHeaderMap(NodeSocket.java:39) ~[classes!/:na]
        at com.higgs.server.web.socket.NodeSocket.receiveMessage(NodeSocket.java:35) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:565) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:520) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:454) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.7.jar!/:5.3.7]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
```
o.s.w.s.m.StompSubProtocolHandler        : Failed to send message to MessageChannel in session xkzneciq:Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.authentication.BadCredentialsException: blank token supplied for web socket request
```

**Comment by Mekadrom** [comment]
needs a new stacktrace example after refactoring

**Comment by Mekadrom** [comment]
nevermind, its been fixed
